# Generated by Django 5.1.2 on 2024-12-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
